### ISSUE TITLE
workspace/save messageBox

### ISSUE THREAD

**Issue by MarkThorley** [radumg/DynaServer#16]
## Situation right now

When you save the file it doesn't tell you this has happened in the Dynamo window other than the star disappearing. 

## What new feature do you suggest ?

Implement a message box that appears in Dynamo to tell the user it has saved.

## How would this feature improve it ?

Dynamo user would be notified too.

## Are you ready to help build this feature ?

Yes

**Comment by radumg** [comment]
will need #24 merged in if we want to keep this notification. I'd say we circle back to it once that's complete as it's not critical.
